-- Tabla para almacenar los registros de actividades personalizadas
CREATE TABLE IF NOT EXISTS `actividad_personalizada` (
  `id_actividad_personalizada` int(11) NOT NULL AUTO_INCREMENT,
  `hora_inicio` time NOT NULL,
  `hora_finalizacion` time NOT NULL,
  `fecha_actividad` date NOT NULL,
  `nombres_apellidos` varchar(255) NOT NULL,
  `genero` varchar(20) NOT NULL,
  `fecha_nacimiento` date NOT NULL,
  `tipo_documento` varchar(50) NOT NULL,
  `numero_documento` varchar(50) NOT NULL,
  `desplazado` tinyint(1) DEFAULT 0,
  `cabeza_hogar_mujer` tinyint(1) DEFAULT 0,
  `cabeza_hogar_hombre` tinyint(1) DEFAULT 0,
  `habitante_calle` tinyint(1) DEFAULT 0,
  `orientacion_sexual` varchar(50) DEFAULT NULL,
  `tipo_discapacidad` varchar(100) DEFAULT NULL,
  `migrante` varchar(10) DEFAULT NULL,
  `mestizo` varchar(10) DEFAULT NULL,
  `afrodescendiente` varchar(10) DEFAULT NULL,
  `indigena` varchar(10) DEFAULT NULL,
  `tipo_seguridad_salud` varchar(50) DEFAULT NULL,
  `condicion_ocupacional` varchar(50) DEFAULT NULL,
  `nivel_estudio` varchar(50) DEFAULT NULL,
  `telefono_celular` varchar(20) DEFAULT NULL,
  `nombre_actividad` varchar(255) NOT NULL,
  `evento_tema` varchar(255) DEFAULT NULL,
  `numero_actividades` int(11) DEFAULT 1,
  `total_masculino` int(11) DEFAULT 0,
  `total_femenino` int(11) DEFAULT 0,
  `firma_data` longtext DEFAULT NULL,
  `fecha_registro` timestamp NOT NULL DEFAULT current_timestamp(),
  `usuario_registro` int(11) DEFAULT NULL,
  PRIMARY KEY (`id_actividad_personalizada`),
  KEY `idx_fecha_actividad` (`fecha_actividad`),
  KEY `idx_numero_documento` (`numero_documento`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
